apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
  # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: "871967969684399"
  # Thermite Certificate retrieval
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: "dde24614-3f90-48eb-9d39-59fb3490075e"
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "b0398fbb289943888365a2af091f9801"
# Non-mandatory parameters
  # Uncomment this for CSP override
  # CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>"