apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
  # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: "420026253910260"
  # Thermite Certificate retrieval
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: "92017d87-1e11-450d-8f7c-b4c20cd866b6"
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "bd33d671ce964e1796eb9e877819da73"
# Non-mandatory parameters
  # Uncomment this for CSP override
  # CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>"
