kind: ConfigMap
apiVersion: v1
metadata:
  name: pan-cni-config
  namespace: kube-system
data:
  cni_network_config: |-
    {
      "cniVersion": "0.3.0",
      "name": "pan-cni",
      "type": "pan-cni",
      "log_level": "debug",
      "appinfo_dir": "/var/log/pan-appinfo",
      "mode": "service",
      "dpservicename": "pan-ngfw-svc",
      "dpservicenamespace": "kube-system",
      "firewall": [ "pan-fw" ],
      "interfaces": ["eth0"],
      "interfacesip": [""],
      "interfacesmac": [""],
      "override_mtu": "",
      "kubernetes": {
          "kubeconfig": "__KUBECONFIG_FILEPATH__",
          "cni_bin_dir": "/opt/cni/bin",
          "exclude_namespaces": [ ],
          "security_namespaces": [ "kube-system"]
      }
    }
